"""Initial schema: vault (folders/tags/secrets/versions), notes + FTS5, activity log, app config.

Revision ID: 0001
Revises:
Create Date: 2026-07-16

Tables are created from the SQLModel metadata directly rather than hand-written
``op.create_table`` calls — the models in ``app/models`` are the single source
of truth for the initial shape. Every *subsequent* migration should be a
normal, explicit Alembic revision (autogenerated or hand-written) so schema
history stays reviewable going forward.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
from sqlmodel import SQLModel

import app.models  # noqa: F401 — registers all table models on SQLModel.metadata

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind)

    # FTS5 external-content index over notes, kept in sync via triggers so
    # application code never has to remember to update it.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5("
        "title, content, content='notes', content_rowid='rowid')"
    )
    op.execute(
        "INSERT INTO notes_fts(rowid, title, content) SELECT rowid, title, content FROM notes"
    )
    op.execute(
        "CREATE TRIGGER notes_ai AFTER INSERT ON notes BEGIN "
        "INSERT INTO notes_fts(rowid, title, content) VALUES (new.rowid, new.title, new.content); "
        "END"
    )
    op.execute(
        "CREATE TRIGGER notes_ad AFTER DELETE ON notes BEGIN "
        "INSERT INTO notes_fts(notes_fts, rowid, title, content) VALUES('delete', old.rowid, old.title, old.content); "
        "END"
    )
    op.execute(
        "CREATE TRIGGER notes_au AFTER UPDATE ON notes BEGIN "
        "INSERT INTO notes_fts(notes_fts, rowid, title, content) VALUES('delete', old.rowid, old.title, old.content); "
        "INSERT INTO notes_fts(rowid, title, content) VALUES (new.rowid, new.title, new.content); "
        "END"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS notes_au")
    op.execute("DROP TRIGGER IF EXISTS notes_ad")
    op.execute("DROP TRIGGER IF EXISTS notes_ai")
    op.execute("DROP TABLE IF EXISTS notes_fts")
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
